INSERT INTO db_product_category (vc_name) VALUES
                                              ('Eletrônicos'),
                                              ('Informática & Acessórios'),
                                              ('Celulares & Smartphones'),
                                              ('Tablets & e-Readers'),
                                              ('TV & Home Theater'),
                                              ('Áudio & Fones'),
                                              ('Câmeras & Drones'),
                                              ('Games & Consoles'),
                                              ('Livros'),
                                              ('Filmes, Séries & Música'),
                                              ('Moda Masculina'),
                                              ('Moda Feminina'),
                                              ('Moda Infantil'),
                                              ('Calçados'),
                                              ('Bolsas & Acessórios'),
                                              ('Joias & Relógios'),
                                              ('Casa & Cozinha'),
                                              ('Móveis & Decoração'),
                                              ('Eletrodomésticos'),
                                              ('Ferramentas & Construção'),
                                              ('Jardim & Varanda'),
                                              ('Esporte & Fitness'),
                                              ('Brinquedos & Hobbies'),
                                              ('Bebês'),
                                              ('Pet Shop'),
                                              ('Beleza & Perfumaria'),
                                              ('Saúde & Cuidados Pessoais'),
                                              ('Mercado & Gourmet'),
                                              ('Papelaria & Escritório'),
                                              ('Automotivo & Moto')
ON CONFLICT (vc_name) DO NOTHING;
